apiVersion: v1
kind: Service
metadata:
  name: yoyo-python-service
spec:
  selector:
    app: yoyo
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yoyo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yoyo
  template:
    metadata:
      labels:
        app: yoyo
    spec:
      containers:
      - name: yoyo
        image: 03022086691/hello-python:latest
        ports:
        - containerPort: 5000
